Adds a new build job to validate all matrix builds passed

diff --git a/.github/workflows/build-and-publish-container-image.yml b/.github/workflows/build-and-publish-container-image.yml
--- a/.github/workflows/build-and-publish-container-image.yml
+++ b/.github/workflows/build-and-publish-container-image.yml
@@ -162,3 +162,21 @@ jobs:
             "KUBECTL_VERSION=${{ matrix.kubectl }}"
             "HELM_VERSION=${{ matrix.helm }}"
             "POWERSHELL_VERSION=${{ matrix.powershell }}"
+
+  matrix_build_check:
+    needs: [build]
+    if: always()
+    runs-on: [ubuntu-latest]
+    steps:
+      - name: Validate all tags built
+        run: |
+          nonSuccessStatuses=$(curl -X GET -s \
+                      -H "Accept: application/vnd.github+json" \
+                      -H "Authorization: Bearer ${{ secrets.READONLY_ACTIONS_GITHUB_PAT }}" \
+                      -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs | jq '.jobs[] | select(.name | startswith("build")) | .conclusion != "success"')
+          if [[ $nonSuccessStatuses == *"true"* ]]; then
+            echo "A build job failed, failing..."
+            exit 1
+          fi
+          echo "All build jobs succeeded"
+          exit 0
